### ISSUE TITLE
How to get projects under a specific namespace/group?

### ISSUE THREAD

**Issue by fuhbar** [gpocentek/python-gitlab#100]
I could not find a way to get a list of projects only of a specific namespace/group. Either its dead simple and I am just blind, or there are in fact some obstacles preventing me of doing so.

**So my question is: Are there any methods providing this functionality and if yes, how do I call them?** 

My investigation brought me to the fact, that the Gitlab API provides 2 methods of searching for projects:

**(1) `/projects/search/:query`**

This API endpoint is the one that python-gitlab queries by calling `gitlab.Gitlab.projects.search()`. The pity is, that this call results (amongst other) in the following SQL query at the Gitlab side (search query:  'foobar'):

```sql
SELECT` COUNT(*)
FROM "projects"
WHERE ((id in (40,12,11,8,7,6) OR visibility_level in (10,20)) AND (name LIKE ('%foobar%')))
```

We can see that the query string is only matched against the project name.

**(2) `/projects?search=:query`**

This is the second way which the Gitlab API provides. The behaviour is - unlike you would have guessed -  different to the one above. One of the resulting SQL queries at the Gitlab instance looks like the following: 

```sql
SELECT "projects"."id"
FROM "projects" INNER JOIN "members" ON "projects"."id" = "members"."source_id"
WHERE "members"."type" IN ('ProjectMember')
    AND "members"."source_type" = 'Project' AND "members"."user_id" = 16))
    AND (LOWER(projects.name) LIKE '%foobar%' OR
                  LOWER(projects.path) LIKE '%foobar%' OR
                  LOWER(namespaces.name) LIKE '%foobar%' OR
                  LOWER(projects.description) LIKE '%foobar%')
    ORDER BY "projects"."created_at" DESC LIMIT 20 OFFSET 0
```
This second method enables us to search for projects by namespace relation. Unfortunately it is not reachable via python-gitlab as far as I see.

**Comment by gpocentek** [comment]
This API is really full of surprises :/

I'm not sure how to deal with this 2 queries in a sensible way, but I'll try to find a solution. Thanks for digging into the problem.

**Comment by fuhbar** [comment]
While coming back to this issue I've noticed, that your implementation is already providing this feature implicitly due to the fact that you can pass arbitrary query parameters to your API, as the function signature of e.g. [`Projects.list(self, **kwargs)`](https://github.com/gpocentek/python-gitlab/blob/master/gitlab/objects.py#L103) suggests.

**(1)** The very straight approach which **failed**:

`gitlab.projects.search('foobar')` translates to `/api/v3/projects/search/foobar`

**(2)** But the think-around-the-corner approach which **succeeds** looks like this: 

`gitlab.projects.list(search='foobar')` translates to `/api/v3/projects?search=foobar`

This issue is obsolete, therefore I am closing it.

**Comment by gpocentek** [comment]
I've added a note in the search() method documentation in commit e48e4ac. Thanks!
