### ISSUE TITLE
Add a User as a member of an existing Project

### ISSUE THREAD

**Issue by Asher256** [gpocentek/python-gitlab#102]
Hi,

It is possible to add a user as member of a Gitlab project with:
```
POST /projects/:id/members
```
(source: http://doc.gitlab.com/ce/api/projects.html#add-project-team-member )

I tried to do that with python-gitlab, but I didn't find a clear way add a user as a member of an existing project. 

I found ProjectMember() and ProjectMemberManager() but these classes are undocumented and they don't look like they were created to the end-users python-gitlab. This is why I'm asking for your help!

Is it possible to add a user as a member of a project? Could you show me how? (I already have the project id + user id)

Thank you Gauvain!

Asher256

**Comment by gpocentek** [comment]
Hi Asher,

The ProjectMember class is the proper class to use:

````` python
p = gl.projects.get(1)
u = gl.projects.get(1)
m = p.members.create({'user_id': u.id, 'access_level': gitlab.Group.MASTER_ACCESS})
`````

The `*_ACCESS` constants should probably be defined somewhere else, but for now it belongs to the `gitlab.Group` class.

Hope this helps.

**Comment by gpocentek** [comment]
Did this work for you?

**Comment by Mingiyan** [comment]
How to add avatar for user in Gitlab? using python
