### ISSUE TITLE
project.save() not working - error 405

### ISSUE THREAD

**Issue by godmar** [gpocentek/python-gitlab#109]
On gitlab 7.4.3, I'm trying to change a project's visibility_level to PRIVATE (0) and save it.

If I do
    p.visibility_level = 0
    p.save()

Where the 'p' object was returned by gitserver.projects.list().
I'm getting:
gitlab.exceptions.GitlabUpdateError: 405: 

When I print the URL, headers, and data created in the update() method, I see:

url https://myserver/api/v3/projects/13
headers {'PRIVATE-TOKEN': 'xxxxx', 'Content-type': 'application/json'}
data: data {"snippets_enabled": false, "name": "xxx", "description": "", "default_branch": "master", "issues_enabled": true, "path": "xxx", "wiki_enabled": true, "visibility_level": 0, "public": false, "merge_requests_enabled": true}

Can this work? I thought the post data needs to contain the project id, as discussed here: http://stackoverflow.com/questions/30293935/gitlab-api-putprojects-id-405-method-not-allowed 
Is this possibly the same issue as issue #68 ?

I don't understand how any of your tests would work with such a bug, however?

**Comment by godmar** [comment]
Re: your request seems to match what's documented here: http://doc.gitlab.com/ce/api/projects.html#edit-project
(i.e., the id does not need to be repeated in the data, just in the url).

Could this be an issue with the gitlab version we have?

**Comment by gpocentek** [comment]
I have not been able to reproduce the problem. Is this still happening for you?

**Comment by godmar** [comment]
Not since we've upgraded out gitlab server. The project save() feature was introduced only in a later version.

I don't know if versioning would be too much effort, but maybe some verbose error when the server returns a 405, as it's likely due to a server not supporting yet what's being asked.

**Comment by gpocentek** [comment]
Gitlab changes a lot so versioning is a solution I'd rather avoid. It's hard enough to keep track of all the updates in master.

I'll close the issue and hope everyone uses a recent gitlab version.

Thank you for your feedback!
