### ISSUE TITLE
Accept an MR with python-gitlab

### ISSUE THREAD

**Issue by vilmosnagy** [gpocentek/python-gitlab#117]
Hi,

It is possible to accept a Merge Request with:

    PUT /projects/:id/merge_requests/:merge_request_id/merge

according to the [docs](http://docs.gitlab.com/ce/api/merge_requests.html#accept-mr).

Is there a way, to do this with python-gitlab?

I have a `ProjectMergeRequest` object by calling `gitlab.project_mergerequests.get(project_id=1, id=1)`, but I cannot find any `accept` method nor field.

Is it possible?

Thanks!

**Comment by vilmosnagy** [comment]
ah, possible duplicate of #105.
would you release a version that has this feature? thanks!

**Comment by gpocentek** [comment]
I release 0.13, you can use the merge() method.
