### ISSUE TITLE
Get artifacts files

### ISSUE THREAD

**Issue by iBobik** [gpocentek/python-gitlab#122]
It seems library is not able to download artifacts (by [/projects/:id/builds/:build_id/artifacts](http://docs.gitlab.com/ce/api/builds.html#get-build-artifacts)), only list them:
```
>>> import gitlab
>>> GITLAB_SERVER = 'https://gitlab.com'
>>> 
>>> gl = gitlab.Gitlab(GITLAB_SERVER, 'xxx')
>>> project = gl.projects.get(123)
>>> build = project.builds.get(12345)               
>>> build.artifacts_file
{'filename': 'artifacts.zip', 'size': 2420515}
```

**Comment by gpocentek** [comment]
Thank you for the report. Could you test the issue-122 branch? I don't have the setup to test right now.

**Comment by iBobik** [comment]
It works, but it is also good to write some docs how to work with it. Maybe some example for not experienced how to convert bytes to files on disk :-)

**Comment by iBobik** [comment]
Also I am not sure if it uses streams, so I can process artifacts bigger than available RAM.

**Comment by gpocentek** [comment]
I have implemented stream support in some methods (the one for which it makes sense to do so) in commit 94aea52. I would be interested in some testing. Do you think you could give it a try?

I've also added some documentation in this commit, published here: http://python-gitlab.readthedocs.io/en/latest/gl_objects/builds.html#streaming-example

**Comment by iBobik** [comment]
I am not sure how to use it in companion with ZipFile stream.

I use it here:
https://github.com/iBobik/gitlab-ci-deployer/blob/master/deployer.py#L50

Could you please kick me to the right direction?



Jan Pobořil

2016-07-17 14:18 GMT+02:00 Gauvain Pocentek <notifications@github.com>:

**Comment by iBobik** [comment]
Btw, is it really needed to have `streamed=True` twice?
```

build.artifacts(streamed=True, streamed=True, action=target)

```



Jan Pobořil

2016-07-17 21:04 GMT+02:00 Jan Pobořil <bobik@ibobik.cz>:

**Comment by gpocentek** [comment]
The double streamed parameter is a mistake, one is enough :)

I'm not sure how to use the stream with ZipFile, I need to dig a little. I'll get back to you with some ideas as soon as I can.

Thank you for testing.
