### ISSUE TITLE
cannot change issue state

### ISSUE THREAD

**Issue by patricochet** [gpocentek/python-gitlab#123]
I have tried 

    git_project = gl.projects.get(issue.gitlab_project.git_project_id)
    git_issue = git_project.issues.get(issue.gitlab_issue_id)
    git_issue.state = "closed"
    git_issue.save()

I do not receive any errors but the state remains the same

**Comment by patricochet** [comment]
I resolved the issue with
    git_issue.state_event = "close"

**Comment by gpocentek** [comment]
The documentation doesn't really help I'm afraid, but the python tests contain some examples. I'm starting an FAQ to try to improve things. Thank you for your feedback.

**Comment by patricochet** [comment]
A FAQ would be greatly appreciated, python-gitlab does quite a bit but can be tricky to figure out at times. Thanks for your hard work
