### ISSUE TITLE
Add 'note_events' or 'comments' to ProjectHook

### ISSUE THREAD

**Issue by rafaeleyng** [gpocentek/python-gitlab#127]
Would it be possible to add attributes for note_events (aka comments) and also Wiki Page events in webhooks?

Scanning through the code I think it should be added here: https://github.com/gpocentek/python-gitlab/blob/master/gitlab/objects.py#L1025

I would like to know whether that's all or if there's more to it. I would gladly try the MR myself in a couple of days.

**Comment by gpocentek** [comment]
Hey,

Yes you can simply add ``note_events`` to the attributes list, it should be enough.

I'm not sure about wiki events though, is it supported by the API?

**Comment by rafaeleyng** [comment]
I don't think wiki events are supported by the API, as [the docs](http://docs.gitlab.com/ce/api/projects.html#add-project-hook) don't state anything about it. But honestly, I'm just interested in note_events, I just mentioned wiki events for completeness sake.

Nice then, I will submit the PR. My first ever contribution in Python, I believe.
