### ISSUE TITLE
ProjectBuild does not have project_id needed for artifacts()

### ISSUE THREAD

**Issue by btashton** [gpocentek/python-gitlab#132]
The ProjectBuild object is missing the project_id attribute that it uses when it makes the call to the gitlab API

Traceback (most recent call last):
  File "gitlabtest.py", line 115, in <module>
    build.artifacts(streamed=True, action=saver)
  File "{SCRUB}/python-gitlab/gitlab/objects.py", line 927, in artifacts
    url = '/projects/%s/builds/%s/artifacts' % (self.project_id, self.id)
AttributeError: 'ProjectBuild' object has no attribute 'project_id'

**Comment by gpocentek** [comment]
Hi,

I've not been able to reproduce the problem. Could you give me a bit more information: python version, python-gitlab version (master I guess), and how did you build your ``build`` object?

Thanks
