### ISSUE TITLE
implement namespaces api

### ISSUE THREAD

**Issue by ajk8** [gpocentek/python-gitlab#133]
Here's is the scenario.  I need to create project X in group Y:

    gitlab.projects.create(name='X', namespace_id=<namespace_id_of_group_Y>)

As far as I can tell, there is no way to reliably infer that value.  Gitlab exposes a simple `namespaces` API which solves the problem.

**Comment by ajk8** [comment]
In case anyone else runs into this, I worked around the problem like this:

```python
# gl is an authenticated gitlab object here
api_url = gl._url + '/namespaces'
response = requests.get(api_url, headers=gl.headers, data={'search': group_name})
if response.status_code != 200:
    raise RuntimeError('could not determine namespace_id for group: ' + group_name)
namespace_id = response.json()[0]['id']
```

**Comment by gpocentek** [comment]
The namespace API is implemented in the master branch (not yet released):

`````python
>>> import gitlab
>>> gl = gitlab.Gitlab.from_config()
>>> gl.namespaces.list(search='root')
[<gitlab.objects.Namespace object at 0x7feb987c1e50>]
>>> gl.namespaces.list(search='root')[0].id
1
`````
