### ISSUE TITLE
More documentation and examples

### ISSUE THREAD

**Issue by Loki-Afro** [gpocentek/python-gitlab#134]
Hi,

maybe it is because I am a python noob, but I would find some examples very helpful :)

**Comment by gpocentek** [comment]
Hi,

I've started to add examples to the documentation recently: http://python-gitlab.readthedocs.io/en/latest/api-objects.html

This is not complete yet, and it takes time, but you should be able to find enough examples to help you get started.

**Comment by dj-wasabi** [comment]
One thing that might also help is checking the `tools/python_test.py` file. :-)

**Comment by gpocentek** [comment]
I have added examples for all the objects (I think). Let me know if something is missing.
