### ISSUE TITLE
project.fork() doesn't exist

### ISSUE THREAD

**Issue by vilhelmen** [gpocentek/python-gitlab#136]
Not sure if it's an oversight, or you just haven't gotten to it (this lib is really helpful and I appreciate all the work!), but project.fork() doesn't seem to exist as the docs suggest:
```python
fork = gl.project_forks.create(project_id=1)
# or
fork = project.fork()
```
```
In [150]: proj = gl.projects.get('test_grp/asdf')

In [151]: proj.fork()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-151-4be540ada96e> in <module>()
----> 1 proj.fork()

AttributeError: 'Project' object has no attribute 'fork'
```

Edit:
I also noticed that the parameter for project_forks.create() is a data dictionary, not a project_id, so the doc should be
```python
fork = gl.project_forks.create({'project_id': 1}) 
```
instead of
 ```python
fork = gl.project_forks.create(project_id=1)
```

**Comment by gpocentek** [comment]
Thanks for your report, the code is there but the doc is not correct. It should be:

`````python
fork = gl.project_forks.create({}, project_id=1)
# or
fork = project.forks.create({})
`````

``project.fork()`` doesn't exist at all.
