### ISSUE TITLE
need a ShareManager

### ISSUE THREAD

**Issue by kneufeld** [gpocentek/python-gitlab#137]
You can share with another group via `project.share(group_id, access_level)` but there is no way (that I can see) to delete a share and/or change the access level of an existing share.

This has something to do with the url `/project/group_links`

Thanks for this great api!

**Comment by gpocentek** [comment]
Hi, thanks for your report.

The only reference to the  group links I found was the ``/projects/share`` endpoint. Could you give me a link to the ``/projects/group_links`` endpoint?

Thank you!

**Comment by kneufeld** [comment]
Yeah, the docs on this seem to be sparse/non-existant.

If you share a project with a group and then go project -> settings -> group then click the `stop sharing` button, the link the button calls is `project/group_links/<id>` with the `DELETE` method.

**Comment by gpocentek** [comment]
I see the link now, but this is not an API call unfortunately, this is only available in the web frontend. Unless this is implemented on the API side I'm afraid I will not be able to add this feature.

**Comment by kneufeld** [comment]
Thanks for looking into it.
