### ISSUE TITLE
Merge Request Accept Returns 404

### ISSUE THREAD

**Issue by afu1979** [gpocentek/python-gitlab#139]
I am able to create and comment on merges but not accept them. One issue may be that I am on v7.1.1 but the API was created on 6.9 according to the release notes. I upgraded to the most recent version of python-gitlab. 

Any ideas?

`            merge = {'source_branch': 'release' , 'target_branch': 'master', 'title': "10.22.0 Release Merge to Master" } 
            currentMerge = project.mergerequests.create(merge)
            print(currentMerge) #this succeeds.
            currentMerge.merge() #this returns a 404
            print(currentMerge)`

Stack Trace

```
Traceback (most recent call last):
  File "C:\Users\brensmith\workspace\ReleaseUtils\src\testmain.py", line 25, in <module>
    currentMerge.merge()
  File "C:\Users\brensmith\Envs\ReleaseUtils\lib\site-packages\gitlab\objects.py", line 1533, in merge
    raise_error_from_response(r, errors)
  File "C:\Users\brensmith\Envs\ReleaseUtils\lib\site-packages\gitlab\exceptions.py", line 168, in raise_error_from_response
    response_body=response.content)
gitlab.exceptions.GitlabOperationError: 404: b'<!DOCTYPE html>\n<html>\n<head>\n  <title>The page you were looking for doesn\'t exist (404)</title>\n  <link href="/static.css" media="screen" rel="stylesheet" type="text/css" />\n</head>\n\n<body>\n  <h1>404</h1>\n  <h3>The page you were looking for doesn\'t exist.</h3>\n  <hr/>\n  <p>You may have mistyped the address or the page may have moved.</p>\n</body>\n</html>\n'


```

**Comment by gpocentek** [comment]
Could you enable the debug output and copy the output (be careful, your auth token will probably appear in the log, so drop it before sending):

`````
gl.enable_debug()
currentMerge.merge()
`````

Thank you.

**Comment by afu1979** [comment]
Thanks for the response and package. Here is the requested logs. I don't
see any tokens.


DEBUG:requests.packages.urllib3.connectionpool:"PUT
/api/v3/projects/116/merge_requests/5280/merge HTTP/1.1" 404 234
header: Date header: Status header: Content-Type header: X-Request-Id
header: X-Runtime header: Vary header: Content-Encoding header:
Content-Length header: Keep-Alive header: Connection Traceback (most recent
call last):
  File "C:\Users\brensmith\workspace\ReleaseUtils\src\testmain.py", line
26, in <module>
    currentMerge.merge()
  File
"C:\Users\brensmith\Envs\ReleaseUtils\lib\site-packages\gitlab\objects.py",
line 1533, in merge
    raise_error_from_response(r, errors)
  File
"C:\Users\brensmith\Envs\ReleaseUtils\lib\site-packages\gitlab\exceptions.py",
line 168, in raise_error_from_response
    response_body=response.content)
gitlab.exceptions.GitlabOperationError: 404: b'<!DOCTYPE
html>\n<html>\n<head>\n  <title>The page you were looking for doesn\'t
exist (404)</title>\n  <link href="/static.css" media="screen"
rel="stylesheet" type="text/css" />\n</head>\n\n<body>\n  <h1>404</h1>\n
 <h3>The page you were looking for doesn\'t exist.</h3>\n  <hr/>\n  <p>You
may have mistyped the address or the page may have
moved.</p>\n</body>\n</html>\n'


On Tue, Aug 30, 2016 at 11:27 AM, Gauvain Pocentek <notifications@github.com

**Comment by gpocentek** [comment]
The URL has changed between the 7.1 release and the master. The URL should be ``/api/v3/projects/116/merge_request/5280/merge`` (singular ``merge_request``). I don't have a proper solution to fix this at the moment, this is a change that probably shouldn't have happened on the gitlab side.

As a workaround you can make a direct call to the API with something like this:

`````
url = '/projects/%s/merge_request/%s/merge' % (currentMerge.project_id, currentMerge.id)
currentMerge.gitlab._raw_put(url)
`````

I have not tested it but it should do the trick.

**Comment by gpocentek** [comment]
I don't think I'll spend time trying to fix this. For older releases of gitlab use the workaround from my previous comment.
