### ISSUE TITLE
Is there a way to add a repository to a group?

### ISSUE THREAD

**Issue by pigeonflight** [gpocentek/python-gitlab#141]
I need to be able to create repositories (projects) that are part of a group.
So instead of gitlab.com/myuser/myrepo
It would be added to gitlab.com/my-group/myrepo

**Comment by gpocentek** [comment]
You need to get the id of the group, then use the ``namespace_id`` attribute to create the group:

`````python
group_id = gl.groups.search('my-group')[0].id
project = gl.projects.create({'name': 'myrepo', 'namespace_id': group_id})
`````

**Comment by derek-austin** [comment]
Please add it to the project documentation.
I tried:
~~~ python
group_id.projects.create({'name': 'project1'})
~~~
and looked into 
~~~ python
pprint.pprint(
    group_id.projects.obj_cls.requiredCreateAttrs,
    group_id.projects.obj_cls.optionalCreateAttrs,
)
~~~ 
for info, but no `'namespace_id'` appeared an I had no clue.

**Comment by gpocentek** [comment]
http://python-gitlab.readthedocs.io/en/stable/gl_objects/projects.html#examples

http://python-gitlab.readthedocs.io/en/stable/api/gitlab.html#gitlab.objects.ProjectManager.create
