### ISSUE TITLE
What do I use to add SSH keys?

### ISSUE THREAD

**Issue by rolfvandam** [gpocentek/python-gitlab#143]
How do I add SSH keys? Theres keys, project_keys and user_keys and they either give me 500, 403 or NotImplemented. Is this even supported yet?

**Comment by gpocentek** [comment]
It depends on what you want to do. If you want to add a keys for the authenticated user you have to use:

`````
gl = gitlab.Gitlab(...)
gl.auth()  # this will create the gl.user object
gl.user.keys.create({'title': 'mykey', 'key': key_content})
`````

If you want to create a key for another user:

`````
gl = gitlab.Gitlab(...)
user = gl.users.get(user_id)
user.keys.create({...})
`````
