### ISSUE TITLE
Syntax for project queries? 

### ISSUE THREAD

**Issue by MikeTheGreat** [gpocentek/python-gitlab#145]
At [http://python-gitlab.readthedocs.io/en/stable/gl_objects/projects.html](http://python-gitlab.readthedocs.io/en/stable/gl_objects/projects.html) the docs specify that I can provide a 'search' parameter in order to narrow down the list of projects.  Specifically, the docs describe search this way:

> search: returns project matching the given pattern

There's a brief code example that shows the use of the search parameter:
```
# Search projects
projects = gl.projects.search('query')
```
I've searched the ReadTheDocs pages for more detail but couldn't find any.  

**Is there a place where the search/query syntax is documented?**

**Comment by gpocentek** [comment]
You can refer to the GitLab API documentation: https://github.com/gitlabhq/gitlabhq/blob/master/doc/api/projects.md

But basically the query is a simple string search in the project name.

**Comment by MikeTheGreat** [comment]
Thank you for your incredibly fast response! :)

I'm very sorry, but I'm new to both GitLab and REST API stuff.  In particular, I'm having a hard time figuring out how to formulate the search criteria (I'm trying to imagine what it would look like as part of a REST / HTTP call, and then how that would look in Python).

What I'd like to do is to get a list of projects that have been forked from a particular project.  I was hoping to do something like this:

`projects =  glc.projects.search('forked-from-project.id=44')`

(Once I figure out the syntax I'll dynamically generate the 44 instead of hard-coding it but for right now I'm just trying something simple)
Since that didn't work I tried to get a 'list' of a single project, in the hopes of getting a simpler query to work. 

This didn't quite work, either:

`projects =  glc.projects.search('id=45')`

In both cases I get an empty list.

Would there happen to be examples of the search query around that I could look at?
  
Is there a block of code that generates the search query that would be informative and not too too hard to dig into?

**I'd love any pointers that could lead me in the right direction but I also want to be respectful of your time.**

And thank you very much for your time and expertise - the API is really, really helpful and it's key to me solving an awesome, interesting problem that I'm enjoying :)

**Comment by gpocentek** [comment]
The GitLab API doesn't provide a search language. The search method is a simple string-based search. For instance ``gls.projects.search('foo')`` would return a list of projects with `foo` in their names.

You have to implement your own solution if you want a more advanced filtering mechanism.

To get a project by id you have to use the `get` method: ``projects = glc.projects.get(45)``.

**Comment by MikeTheGreat** [comment]
Aha!  That makes sense (both with the documentation and from what I could in the source code I was digging through).  

For some reason I saw the word 'query' and assumed it was a generalized, ORM/Linq/etc sort of thing.

I'll stick with my original plan to just iterate all the projects & look for those that are forked from the target repo, and then work with just those.

Thank you very much for all your help with this!

**Comment by gpocentek** [comment]
Glad I could help!
