### ISSUE TITLE
Extracting data from a gitlabObject

### ISSUE THREAD

**Issue by pedrocaseiro** [gpocentek/python-gitlab#149]
I'm doing the following
```
projects = gl.projects.list()
for project in projects:
    print(project.branches.list())
```

And I'm getting the following answer
`[<gitlab.objects.ProjectBranch object at 0x110316a90>]
`
How can I turn this into a non gitlab project, such as a string?

**Comment by gpocentek** [comment]
There's no method to serialize objects as strings. It really depends on what you want to achieve. You will have to use the ProjectBranch attributes. For instance if you want to return the branch names:

`````
for project in projects
    print([b.name for b in project.branches.list])
`````

You can find the available attributes withe the ``vars()`` function, or using ``help(object)``.
