### ISSUE TITLE
gitllab project all pagination ?

### ISSUE THREAD

**Issue by jrevillard** [gpocentek/python-gitlab#153]
Would it be possible to implement the pagination for this command please?

Best,
Jerome

**Comment by gpocentek** [comment]
Do you mean this:

`````
gl = gitlab.Gitlab(...)
all_projects = gl.projects.all(all=True)
`````

**Comment by jrevillard** [comment]
Hi,

No I was speaking about the CLI.

Best,
Jerome

**Comment by gpocentek** [comment]
I can probably do something about it.

**Comment by jrevillard** [comment]
Thanks!

**Comment by jrevillard** [comment]
Dear @gpocentek,

Thanks for the modification but my request was more about the ` def do_project_all(self, cls, gl, what, args)` CLI command which do not have any pagination at all.

Best,
Jerome

**Comment by gpocentek** [comment]
ah right, I missed that.

**Comment by obillard** [comment]
Hi all !
Unfortunately, I cannot contribute to this issue (not a Python dev), but am really interested in the resolution :).
