### ISSUE TITLE
can't delete a merge request

### ISSUE THREAD

**Issue by zolij** [gpocentek/python-gitlab#157]
Hello,

I'm trying delete a merge request, but I get status code 405:
`gl = gitlab.Gitlab(<url>, <token>)`
`project = gl.projects.get(5259)`
`project.mergerequests.delete(8231)`

However if I do with curl (/api/v3/projects/5259/merge_requests/8231), it works like a charm.

What's the problem?

Thanks

**Comment by gpocentek** [comment]
This is somehow related to #139, a change in the API on the gitlab side. I'll just drop the support for older gitlab versions.

**Comment by sjf546339672** [comment]
How to solve it

**Comment by sjf546339672** [comment]
> Hello,
> 
> I'm trying delete a merge request, but I get status code 405:
> `gl = gitlab.Gitlab(<url>, <token>)`
> `project = gl.projects.get(5259)`
> `project.mergerequests.delete(8231)`
> 
> However if I do with curl (/api/v3/projects/5259/merge_requests/8231), it works like a charm.
> 
> What's the problem?
> 
> Thanks

Excuse me, How did you solve it

**Comment by max-wittig** [comment]
The API v3 is not supported anymore, either Gitlab nor by python-gitlab. You'll need to use the v4 API. If you maintain your Gitlab instance, please upgrade to the latest version.
