### ISSUE TITLE
Can't delete merge request

### ISSUE THREAD

**Issue by dosmachko** [gpocentek/python-gitlab#161]
Hi, I was trying to delete merge request, once it was merged or closed
but every time I got error

_405 Method Not Allowed - The request is not supported_

I've used this documentation. https://python-gitlab.readthedocs.io/en/stable/gl_objects/mrs.html
Update and Save method works fine.
Could you please help me with this issue?

**Comment by gpocentek** [comment]
I'm not sure that this is related to python-gitlab, but I can be wrong. I wiill test and give you feedback as soon as I can.

**Comment by gpocentek** [comment]
This works fine for me. Maybe this API is not supported in the gitlab version you are using.

**Comment by gpocentek** [comment]
I'm closing this issue but feel free to reopen if you think this really is a python-gitlab problem.
