### ISSUE TITLE
pagination support

### ISSUE THREAD

**Issue by glensc** [gpocentek/python-gitlab#164]
General API Documentation mentions paging:

https://docs.gitlab.com/ce/api/

Sometimes the returned result will span across many pages. When listing resources you can pass the following parameters:

Parameter | Description
------------ | -------------
page	| Page number (default: 1)
per_page	| Number of items to list per page (default: 20, max: 100)

however this does not seem to be supported:

```
gl.users.list({'per_page': 100})]
TypeError: list() takes exactly 1 argument (2 given)
```

and if i do not specify the parameter, it returns always 20 users

**Comment by gpocentek** [comment]
Hi,
Maybe this will help: http://python-gitlab.readthedocs.io/en/stable/api-usage.html#pagination

**Comment by glensc** [comment]
oops. indeed, seems logical to be also on general page for this project.

but i already rewrote the code to check each user one by one, because limit 100 would be too small for me. and was easier to do so than add multiple page support :)
