### ISSUE TITLE
is there a method to list all files under a project?

### ISSUE THREAD

**Issue by githubfun** [gpocentek/python-gitlab#167]
from the documentation, http://python-gitlab.readthedocs.io/en/stable/gl_objects/projects.html?highlight=project_files, I don't seem to find any. Thanks!

**Comment by gpocentek** [comment]
Hi!

You can use ``repository_tree()`` to get the files. This doesn't work recursively though, so you'll have to iterate on ``tree``-type items if you want to go down the tree:

`````python
>>> for i in p.repository_tree(): print i
... 
{u'mode': u'040000', u'type': u'tree', u'id': u'3bae202445a0f8acc4e9ed592da63d674d142f65', u'name': u'source'}
{u'mode': u'100644', u'type': u'blob', u'id': u'b25c15b81fae06e1c55946ac6270bfdb293870e8', u'name': u'.gitignore'}
>>> source_content = p.repository_tree(path='source')
`````

**Comment by githubfun** [comment]
Thank you! I should have Repository section instead of the Files section.
