### ISSUE TITLE
Creating hooks with a secret token

### ISSUE THREAD

**Issue by dj-wasabi** [gpocentek/python-gitlab#170]
I'm busy with creating some Ansible modules for doing things like, creating groups, users and projects in Gitlab. That all works perfectly, but now I'm busy with adding a webhook to a project. And specifically, configuring a webhook with a secret token.

Is this possible? I can't find it in the documentation. I was hoping to create a webhook with a secret token and I hope to be able to validate if the token is what it supposed to be.

Thanks in advance.

**Comment by gpocentek** [comment]
From what I see in the docs and in the gitlab code defining a token for a hook is not supported by the Gitlab API, so I will not be able to add this feature in ``python-gitlab``.

You can probably report a bug on Gitlab to request this feature.

**Comment by gpocentek** [comment]
FYI: https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/7063

**Comment by dj-wasabi** [comment]
Many thanks! Hope that it will be merged soon. 👍

**Comment by smcgivern** [comment]
@dj-wasabi I've just picked this up, I hope to get it in GitLab 8.14. I have one question for you:

> I was hoping to create a webhook with a secret token and I hope to be able to validate if the token is what it supposed to be.

The way I'm implementing this is that we don't echo the token back, would this be a blocker for you? We don't show the token in the UI, so I'd like the API and UI to be consistent - and only showing the token on update adds some extra complexity to the API. Let me know what you think!

**Comment by pelallemant** [comment]
@smcgivern You don't have to make the token public. In the UI you can't look at it once you created the webhook, you should not allow the token to be available when fetching webhooks.

**Comment by dj-wasabi** [comment]
@smcgivern No, its not a big deal. I only want to create a webhook and configure a secret token. If is not a big deal if I can read it, I just can update the Ansible module with a extra option to force the secret token update on every run or not.

**Comment by smcgivern** [comment]
This has been merged, it will be in GitLab 8.14: https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/7220

Thanks @gpocentek!

**Comment by gpocentek** [comment]
@smcgivern Great! thank you :)

**Comment by dj-wasabi** [comment]
Thanks al!

**Comment by drzraf** [comment]
@dj-wasabi https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/7220#note_71782207
