### ISSUE TITLE
Kwargs always overwrite response data

### ISSUE THREAD

**Issue by hedderich** [gpocentek/python-gitlab#171]
When requesting issues filtered by labels, they never contain the actual labels. Instead they contain only the ones provided as a filter.

Consider the following setup:
```python
>>> client = gitlab.Gitlab(...)
>>> issues = client.project_issues.list(project_id=123))
>>> len(issues)
5
>>> issues[0].labels
{'somelabel', 'another', 'evenmore'}
```
Now when you filter for a specific label, the result contains the correct amount of issues, but is missing all the remaining labels:
```python
>>> issues = client.project_issues.list(project_id=123, labels=set(['somelabel']))
>>> len(issues)
2
>>> issues[0].labels
{'somelabel'}
```

**Comment by gpocentek** [comment]
Nice catch, definitely a bug in python-gitlab. Thanks for the report.
