### ISSUE TITLE
mr.merge  is report 404

### ISSUE THREAD

**Issue by HongYuanLi1989** [gpocentek/python-gitlab#173]
the debug url is /api/v3/projects/148/merge_requestd/335/merge/  and report 404 ,but i use curl in terminal the url is /api/v3/projects/148/merge_request/335/merge  is that gitlab changes?  gitlab version is 8.4.1。 thx

**Comment by gpocentek** [comment]
Please see https://github.com/gpocentek/python-gitlab/commit/cb30dd1d4caaba03f464cdf5751ef0336f8a6c33 for some explanation about the MR situation.

Thanks.

**Comment by HongYuanLi1989** [comment]
Thanks
