### ISSUE TITLE
Can't enable project features

### ISSUE THREAD

**Issue by chrwen-omicron** [gpocentek/python-gitlab#181]
For some reason I can't enable project features like merge requests or LFS anymore. I don't get an error, it simply doesn't change the setting. There are no problems with disabling features.
Can somebody confirm this?

**Comment by chrwen-omicron** [comment]
btw I'm using GitLab 8.12.7 with python-gitlab 0.16

**Comment by gpocentek** [comment]
Same problem here, thank you for the report.

**Comment by chrwen-omicron** [comment]
I had a quick look at it, but couldn't find the problem.
How do you debug GitLab and python-gitlab?

**Comment by Normo** [comment]
Hey,
same problem with GitLab 8.13.6 and python-gitlab 0.16.

**Comment by gpocentek** [comment]
I'll release 0.18 this week, with the fix for this bug.

**Comment by gpocentek** [comment]
I use the `gitlab.enable_debug()` method for debug. It displays the requests sent to the gitlab server.
