### ISSUE TITLE
bad artifacts zip file

### ISSUE THREAD

**Issue by obelix05** [gpocentek/python-gitlab#194]
I use the code-example from http://python-gitlab.readthedocs.io/en/latest/gl_objects/builds.html#streaming-example to download artifacts from gitlab. There is no error by doing this and the size of the zip-file is also correct. But it is a bad zipfile. If i open it with 7-zip, there is only one folder, one subfolder and a file with size "0". If I try to open it with the windows Explorer, the error "the compressed (zipped) folder ... is invalid." occured.
Is there any idea to solve this problem?

**Comment by obelix05** [comment]
the solution is to open the zip-file in binary-mode (yes i am using windows :) )
`self._fd = open('artifacts.zip', 'wb')`

**Comment by gpocentek** [comment]
Thnk you for your feedback. I'll update the doc.
