### ISSUE TITLE
Enable an existing deploy key

### ISSUE THREAD

**Issue by smelchior** [gpocentek/python-gitlab#196]
Currently i can only disable / enable deploykeys that have been created with the project. I have an existing deploy key that is already in use in other projects which i want to enable. But i get an exception in that case:
gitlabProject.keys.enable(12)

AttributeError: 'ProjectKeyManager' object has no attribute 'enable'

Is there a way to make this possible?

**Comment by gpocentek** [comment]
At the moment you need to retrieve the key, then use its ``enable`` method:

`````
key = gitlabProject.keys.get(12)
key.enable() 
`````

No ``enable`` method exist on the manager object (``keys`` in your example).

**Comment by lordi** [comment]
I do think this is broken currently. There seems to be no way to enable a deploy key for a project. I'm also getting a 404 on ``.get()``.

**Comment by smelchior** [comment]
I guess the get call for the key is not really supported for the gitlab api. The only way to do it seems to be:
https://docs.gitlab.com/ee/api/deploy_keys.html#enable-a-deploy-key
which would map to:
`gitlabProject.keys.enable(12)`
but that is not working due to the exception:
`AttributeError: 'ProjectKeyManager' object has no attribute 'enable'`
