### ISSUE TITLE
API docs: Pagination starts at 1

### ISSUE THREAD

**Issue by jpparis-orange** [gpocentek/python-gitlab#197]
It seems to me that  ``gl.groups.list(page=0, per_page=10)`` and  ``gl.groups.list(page=1, per_page=10)`` return the same result. Page is one-based.

But, in the [pagination)[http://python-gitlab.readthedocs.io/en/stable/api-usage.html#pagination] section, the code sample uses ``page=0``. This may induce that page is zero-based.

**Comment by gpocentek** [comment]
Nice catch, thank you for the bug report.
