### ISSUE TITLE
gitlab project --create can't create project anymore

### ISSUE THREAD

**Issue by githubfun** [gpocentek/python-gitlab#199]
it used to work but stopped working now. Upgrading to 0.17 still doesn't work.

gives me message
```
id: None
path: None
```

**Comment by githubfun** [comment]
I've verified however the non command line version
 `gl.projects.create({'name': name, 'namespace_id': id})` still works

**Comment by gpocentek** [comment]
The CLI doesn't do as much filtering as the library and sends a lot of information to the server. Looks like most of it cannot be handled on the server side since gitlab 8.15.
