### ISSUE TITLE
cannot create or save issue

### ISSUE THREAD

**Issue by papagandalf** [gpocentek/python-gitlab#200]
Hello, I'm trying to use python-gitlab for a gitlab.com repo.
When I try to edit an issue by 
```
issue = gl.project_issues.get(ID, project_id=PROJECT_ID)
issue.title = "TEST TITLE"
issue.save()
```

the issue does not change at all.
When I try to create a new one by 
```
issue = gl.project_issues.create({'title': 'I have a bug', 'description': 'desc'}, project_id=PROJECT_ID)
```
I get a 200 request response, with details from the last created issue instead of a 201 response (and nothing gets created).
Listing current projects and issues works fine.
Am I doing something wrong?

**Comment by gpocentek** [comment]
Hi,

You snippets look good, and they work for me. Have you tried with the latest python-gitlab version?

What is your gitlab server version?

**Comment by papagandalf** [comment]
I don't have a gitlab server set up, I use gitlab.com for hosting my repos, so I suppose it is 8.15?

**Comment by gpocentek** [comment]
I've tested with a project on gitlab.com, it works fine for me with python-gitlab 0.18. Could you test again, maybe there's been a temporary problem on the gitlab side?

**Comment by papagandalf** [comment]
I found the source of the problem: when I was creating the gitlab object, I used "http://gitlab.com" instead of "https://gitlab.com", so the API was redirecting me to https, thus performing a GET request on /issues and not a POST. Thanks for helping out!
