### ISSUE TITLE
Can't search an issue with its iid

### ISSUE THREAD

**Issue by chilwalkishan** [gpocentek/python-gitlab#201]
Is there to search issues with there iid?

issue = gl.project_issues.get(iid, project_id=1)
or
issue = project.issues.get(iid)

doesn't fetch results.

**Comment by gpocentek** [comment]
Yes, you need to use ``list()`` with a filter:
`````python
issue = project.issues.list(iid=wanted_iid)[0]
`````
``list()`` returns a list obviously, so the issue you're looking for is the first item (if found).

`````python
>>> p.issues.list()
[<ProjectIssue id:4>, <ProjectIssue id:3>]
>>> p.issues.list(iid=1)
[<ProjectIssue id:3>]
`````
