### ISSUE TITLE
Support for multiple files and actions in a commit

### ISSUE THREAD

**Issue by adinriv** [gpocentek/python-gitlab#206]
Do you support the multiple files and actions payload somehow? 
Couldn't find that feature in the documentation.

I'm asking about the feature introduced in 8.13 (https://docs.gitlab.com/ce/api/commits.html).

**Comment by gpocentek** [comment]
This is not yet implemented but I'll work on this feature. Thanks.

**Comment by adinriv** [comment]
Hi, thanks for the reply!

Quick question, as you close it should I assume it is implemented? Or that it will be implemented somewhere in the future?

I'm testing it and I get an `NotImplementedError`, so I'm not sure if I'm using it wrong or if it will be implemented later.

**Comment by gpocentek** [comment]
It's implemented on the master branch, you will need to install from the git repo.
