### ISSUE TITLE
`AttributeError` on projects within groups

### ISSUE THREAD

**Issue by adinriv** [gpocentek/python-gitlab#209]
I'm testing the creation of files through the API and when the files has a path directory that needs to be created, the API returns an AttributeError.

Note that using the GitLab `POST` (https://docs.gitlab.com/ee/api/repository_files.html#create-new-file-in-repository) successfully creates the file and the needed path.

**Comment by gpocentek** [comment]
Hi,

Could you provide a code sample to reproduce this problem? Thanks.

**Comment by adinriv** [comment]
Check the snippet below. While doing this test I noticed that the error changed, and I'm continue debugging the type of error that I see in the full script.

However, here there is another error (it gives a `403`) but the files are created. I will continue debugging and get an Minimal Working Example for you.

```
import gitlab

gl = gitlab.Gitlab.from_config('gitlab.com', ['./gl.cfg'])

# Look for a global test project on my user
# Note that if the repo is empty the API doesn't even connect
projects = gl.projects.search('test-files')

for project in projects:
  project.files.create({
      'file_path': '.gitlab/issue_templates/test-1.md',
      'branch_name': 'master',
      'content': '# Test 1',
      'commit_message': 'Create test 1 template'
    })

# Error (however, the file is created)
# ======
#   Traceback (most recent call last):
#   File "/home/adin/bin/gitlab-template/test.py", line 14, in <module>
#     'commit_message': 'Create test 1 template'
#   File "/usr/local/lib/python3.5/dist-packages/gitlab/objects.py", line 144, in create
#     return self.obj_cls.create(self.gitlab, data, **args)
#   File "/usr/local/lib/python3.5/dist-packages/gitlab/objects.py", line 358, in create
#     obj.save()
#   File "/usr/local/lib/python3.5/dist-packages/gitlab/objects.py", line 328, in save
#     self._create(**kwargs)
#   File "/usr/local/lib/python3.5/dist-packages/gitlab/objects.py", line 313, in _create
#     json = self.gitlab.create(self, **kwargs)
#   File "/usr/local/lib/python3.5/dist-packages/gitlab/__init__.py", line 513, in create
#     raise_error_from_response(r, GitlabCreateError, 201)
#   File "/usr/local/lib/python3.5/dist-packages/gitlab/exceptions.py", line 180, in raise_error_from_response
#     response_body=response.content)
# gitlab.exceptions.GitlabCreateError: 403: 403 Forbidden

  project.commits.create({
    'branch_name': 'master',
    'commit_message': 'Create several templates',
    'actions': [
      {
        'action': 'create',
        'file_path': '.gitlab/issue_templates/test-2.md',
        'content': '# Test 2'
      },
      {
        'action': 'create',
        'file_path': '.gitlab/issue_templates/test-3.md',
        'content': '# Test 3'
      }
    ]})

# Error  (however, the files are created)
# ======
# Traceback (most recent call last):
#   File "/home/adin/bin/gitlab-template/test.py", line 47, in <module>
#     'content': '# Test 3'
#   File "/usr/local/lib/python3.5/dist-packages/gitlab/objects.py", line 144, in create
#     return self.obj_cls.create(self.gitlab, data, **args)
#   File "/usr/local/lib/python3.5/dist-packages/gitlab/objects.py", line 358, in create
#     obj.save()
#   File "/usr/local/lib/python3.5/dist-packages/gitlab/objects.py", line 328, in save
#     self._create(**kwargs)
#   File "/usr/local/lib/python3.5/dist-packages/gitlab/objects.py", line 313, in _create
#     json = self.gitlab.create(self, **kwargs)
#   File "/usr/local/lib/python3.5/dist-packages/gitlab/__init__.py", line 513, in create
#     raise_error_from_response(r, GitlabCreateError, 201)
#   File "/usr/local/lib/python3.5/dist-packages/gitlab/exceptions.py", line 180, in raise_error_from_response
#     response_body=response.content)
# gitlab.exceptions.GitlabCreateError: 403: 403 Forbidden
```

**Comment by adinriv** [comment]
@gpocentek were you able to reproduce the error?

**Comment by gpocentek** [comment]
@adinriv I've not been able to reproduce the file creation problem (without groups). I tested with python2.7 and python3.5. Gitlab returns a 201 code, which is expected. Could it be a specific setup on your gitlab server? Here's the code I used (added some debug to get the return code):

`````python
>>> import gitlab
>>> gl = gitlab.Gitlab.from_config('local')
>>> p = gl.projects.get(1)
200
>>> p.files.create({'file_path': 'gitlab/1/1.md', 'branch_name': 'master', 'content': 'test', 'commit_message': 'test'})
201
<ProjectFile id:None>
`````

There's a problem with groups though, an attribute/method conflict. I wouldn't try to use group.projects for now.

**Comment by adinriv** [comment]
@gpocentek I just re tested the file creation on repos without groups, and it is working now. Maybe some problem with `gitlab.com` on that time.

However, as you mentioned, there is an error with the attributes. Is there another way to access the `group.projects`?

**Comment by gpocentek** [comment]
There's no solution yet for the group.projects access I'm afraid. I need to find some kind of workaround.

**Comment by adinriv** [comment]
Hi, can we expect this bug to be fixed "soon"?

**Comment by gpocentek** [comment]
@adinriv could you check if commit 35339d6 is OK for you? It fixes the somewhat unpredictable behavior of group.projects but I had to make a choice: keep the current list of projects or use the manager object. The latest seemed to be the more logical choice.

Thanks!

**Comment by adinriv** [comment]
Did you update the documentation? Can't find a way on how to use the new `GroupProject`?

**Comment by gpocentek** [comment]
I might have mixed up things. The commit fixes the group.projects issue (attribute/member conflict).

I'll have to have a closer look at your other problem soon.

**Comment by adinriv** [comment]
I think I got it, but it is really a huge work around, as you query for objects multiple times. Maybe you can enlighten me or give a correct way of accessing.

So, basically, the `gps = group.projects.list()` returns a list of `GroupProject`s that solves the attribute error from before. But you need to convert each element into a `Project` object. I don't know if you can cast it easily, can you?

So, what I did was to query GitLab again through `gl.projects.get(gp.id)` where `gp` is an element from `gps`. 

My problem is that you query GitLab multiple times to get the projects, as you already got the `GroupProject`s information. Maybe I'm wrong, so can you give some insight if there is a better way to do this?

**Comment by gpocentek** [comment]
OK I see what you mean. ``group.projects.list()`` should return ``Project`` objects, it would obviously make more sense. My problem here is that without ``GroupProject`` objects I lose the possibility to filter the projects listing with a consistent API. I could implement a ``list_projects()`` method but it doesn't feel right.

Let me sleep on it and I'll see what I can do to improve the situation. If you have ideas or think of another way of changing the current implementation don't hesitate to share :)

Thank you for you tests and patience!

**Comment by gpocentek** [comment]
@adinriv could you check the issue/209 branch and tell me if matches what you expect? Thanks again.

**Comment by adinriv** [comment]
Is there a way to test the branch without having to reinstall it through `pip`? Can I use your test suit for that?

**Comment by gpocentek** [comment]
Looks like pip can manage installations from git branches: http://stackoverflow.com/questions/20101834/pip-install-from-git-repo-branch

Something like ``pip install git+https://github.com/gpocentek/python-gitlab.git@issue/209``

**Comment by gpocentek** [comment]
@adinriv I merged the change, I think it should fix your problem.

Please let me know if it's OK, I'll probably a release soon. Thank you.

**Comment by yolfer** [comment]
Hello, any idea when a version that includes this fix will be released? Thanks!
