### ISSUE TITLE
FR: Add a function to get the merge requests URL to ProjectMergeRequest

### ISSUE THREAD

**Issue by testing-in-chrome** [gpocentek/python-gitlab#211]
It would be great and very useful if we can get the URL of the merge request from the MR object. So something for example like:

mr = project.mergerequests.create({'source_branch': 'cool_feature',
                                                          'target_branch': 'master',
                                                          'title': 'merge cool feature'})
print("Merge request created at: " + mr.url())

Here is an example of how PyGithub is doing it: http://pygithub.readthedocs.io/en/latest/github_objects/PullRequest.html#github.PullRequest.PullRequest.url
------
In page: gl_objects/mrs.rst

**Comment by gpocentek** [comment]
Unless I misunderstood you request you are looking for ``mr.web_url``.

**Comment by testing-in-chrome** [comment]
Yes. Do we have that already? I couldn't find `mr.web_url` anywhere in the docs. Maybe I missed it?

**Comment by gpocentek** [comment]
Because of the dynamic creation of objects in python-gitlab, documenting every attribute is quite complicated. To see all the available attributes you can use ``mr.__dict__`` or ``vars(mr)``.

And yes, ``mr.web_url`` is available.
