### ISSUE TITLE
gl.keys.get(id) doesn't return key

### ISSUE THREAD

**Issue by loockass** [gpocentek/python-gitlab#212]
When I'm trying to get info about deploy key using key id of another user using root token result is empty.
gl.keys.list(all=True) returns keys only for root user.

Although
GET https://gitlab.domain/api/v3/keys/124?private_token=blabla in rest client works fine.

**Comment by gpocentek** [comment]
I've tested locally and haven't been able to reproduce the problem.

Have you verified that the keys you're trying to list are really deploy keys, and not the user's own keys?

**Comment by gpocentek** [comment]
BTW your GET example is not accessing a deploy key, the URL would be ``/v3/deploy_keys/...``.

**Comment by loockass** [comment]
Yep, you're right. It was my fault.

But don't you think that 'keys' may be a little ambiguous name for this since we can list users own keys via api using `keys` in GET? And is there any possibility to do this with python-gitlab?

**Comment by gpocentek** [comment]
Yes I agree, using ``gl.keys`` is probably not the best idea. I could probably add a deploykeys attribute.

The user own keys can be listed using the ``gl.user.keys`` manager:
`````python
>>> gl.auth()  # makes sure that gl.user is created
>>> gl.user.keys.list()
[<CurrentUserKey id:1>]
`````
