### ISSUE TITLE
Issues state error when kwarg is set

### ISSUE THREAD

**Issue by lives** [gpocentek/python-gitlab#213]
There is an opened issue at gitlab 'API - /groups/issues behaves differently that in API doc' https://gitlab.com/gitlab-org/gitlab-ce/issues/23655

According to a comment on this issue, there are 3 different states to filter Issues collections, https://gitlab.com/gitlab-org/gitlab-ce/blob/v8.13.0/app/finders/issues_finder.rb#L9

With current 0.18 python-gitlab, if we call :
```
# group is a gitlab group
issues = group.issues.list(state="all", page=1, per_page=1024)
for i in issues:
    print i.state
```
All the returned issue states will be "all" instead of respective "opened", "reopened" or "closed".

If you replace line https://github.com/gpocentek/python-gitlab/blob/0.18/gitlab/__init__.py#L334 by
`results = [cls(self, item) for item in r.json()`

It works, but I fear it will create regressions will it ?

**Comment by gpocentek** [comment]
Thank you for the report.

Your suggestion works but would indeed create regressions for other objects.

**Comment by gpocentek** [comment]
Actually I've not been able to reproduce the problem:

`````python
>>> group = gl.groups.get(6)
>>> issues = group.issues.list(state="all")
>>> for i in issues:
...     print i.state
... 
opened
opened
`````

I've tested on a 8.15 gitlab installation with the master branch of python-gitlab.

**Comment by lives** [comment]
En effet avec la master tout fonctionne correctement.
