### ISSUE TITLE
Can't create variables on a project

### ISSUE THREAD

**Issue by alexwidener** [gpocentek/python-gitlab#218]
Hi, given the following: 

```
self.gitlab.project_variables.create({'key': 'key1', 'value': 'value1'}, project_id=project.id)
```

Where self.gitlab is the Gitlab authenticated instance and project.id is the correct id to the project, 
I am incapable of creating Project Variables. 

This is nearly identical to the documentation here: http://python-gitlab.readthedocs.io/en/stable/gl_objects/builds.html?highlight=variable#id1

It's raising with an error code of 200:
```
gitlab.exceptions.GitlabCreateError: 200: []
```
inside of raise_error_from_response. 

Curious if it's just me not realizing something that I'm doing incorrectly.

**Comment by alexwidener** [comment]
Apparently it won't create project variables without https on the gitlab url, but it will create projects. 

Issue solved.

**Comment by dave5623** [comment]
Literally about to create a similar issue with regards to failing to create a file. Double checked and it was because I wasn't using HTTPS.

Might be worth documenting this in the readthedocs site.
