### ISSUE TITLE
Is there a way to get more than 20 merge requests for one project?

### ISSUE THREAD

**Issue by rolisanchez** [gpocentek/python-gitlab#225]
I am running the following command:

`mrs = gl.project_mergerequests.list(project_id=1)`

What I want is to return all the merge requests for that project (I am expecting >100 merge requests). However, this is only returning 20 merge requests. (I realized that 20 is the number of merge requests returned per page when browsing through the GitLab website, does this have anything to do?). 

Any help is appreciated :)

**Comment by gpocentek** [comment]
Yes, you need to use pagination. Usage is explained in the docs: http://python-gitlab.readthedocs.io/en/stable/api-usage.html#pagination

Let me know if this helps.

**Comment by rolisanchez** [comment]
Exactly! Thanks! :)
