### ISSUE TITLE
Can't get all builds for a commit

### ISSUE THREAD

**Issue by rasup** [gpocentek/python-gitlab#233]
I want to get all builds for a specific commit but using the following code results in an exception:
```python
    gl = gitlab.Gitlab(url, ssl_verify=False, private_token=api_token)
    commit = gl.project_commits.get(sha, project_id)
    builds = commit.builds(all=True)
```
Exception:
```
    builds = commit.builds(all=True)
  File "C:\Users\rup\AppData\Local\Programs\Python\Python35-32\lib\site-packages\gitlab\objects.py", line 1354, in builds
    **kwargs)
  File "C:\Users\rup\AppData\Local\Programs\Python\Python35-32\lib\site-packages\gitlab\__init__.py", line 340, in _raw_list
    results.extend(self.list(cls, **args))
  File "C:\Users\rup\AppData\Local\Programs\Python\Python35-32\lib\site-packages\gitlab\__init__.py", line 391, in list
    ", ".join(missing))
gitlab.exceptions.GitlabListError: Missing attribute(s): project_id
```

Am I doing something wrong?

To get the job done I currently use the following workaround (The commit has less than 1000 builds):
```
    builds = commit.builds(page=1, per_page=1000)
```

**Comment by gpocentek** [comment]
Hello,

I've not been able to reproduce this problem, but it reminds me of a fixed bug;

Could you give me a bit more information about your setup: python version, operating system, and python-gitlab version?

Thank you.

**Comment by rasup** [comment]
Hi,

Sorry for not providing the info in my first message, but here it is :-):
```
OS: Windows 7
Python: 3.5.2
python-gitlab: 0.19
```

**Comment by gpocentek** [comment]
I needed more builds, I can now reproduce the issue.
