### ISSUE TITLE
Implement API for cherry picking commits

### ISSUE THREAD

**Issue by cgumpert** [gpocentek/python-gitlab#235]
Hi,

the Gitlab API provides a functionality for [cherry-picking](https://docs.gitlab.com/ce/api/commits.html#cherry-pick-a-commit) individual commits. This is not yet implemented in the nice python wrapper. Could this functionality be added?

Thanks,
Christian

**Comment by gpocentek** [comment]
#236 has been merge, thanks :+1:

**Comment by cgumpert** [comment]
Hi @gpocentek, do you have an idea when the next release containing this enhancement will be available?
