### ISSUE TITLE
Slack Service is Slash Commands or Notifications?

### ISSUE THREAD

**Issue by astronouth7303** [gpocentek/python-gitlab#259]
There's only one slack service I could find in the API, but there's multiple slack integrations in the web UI.

What's going on?

**Comment by astronouth7303** [comment]
It's slack notification. I don't think I see support for `slack-slash-commands`.

**Comment by gpocentek** [comment]
I don't see more services in Gitlab's API code, so there's not a lot I can do about it. You should consider reporting an issue on Gitlab if you need more features in the API.
