### ISSUE TITLE
Generate read the docs documentation

### ISSUE THREAD

**Issue by vccabral** [gpocentek/python-gitlab#48]
I starting using this API a few days ago but have found myself digging through the code to learn how to do more exotic functions such as automatically create a branch in an existing gitlab repo. As I go through the code, I would love to create documentation based on my learning experience.

**Comment by nblock** [comment]
The content at readthedocs is not up-to-date with the docs in the repository.

**Comment by gpocentek** [comment]
This is fixed now. Thanks for the heads up.

**Comment by gpocentek** [comment]
The RTD project is setup, and we have some documentation. We need to improve it but the initial setup seems good enough to me.
