### ISSUE TITLE
Support for pagination?

### ISSUE THREAD

**Issue by godmar** [gpocentek/python-gitlab#53]
all_projects() returns only the first page of results.

The GitLab API documentation says to use the next/pref links in there, and that at most 100 results are returned per page.

Is pagination to obtain all results supported - otherwise, methods like 'all_projects' would be useless.

**Comment by gpocentek** [comment]
Pagination is supported. you can use the --per-page and --page options:

```
./gitlab project list --per-page 2 --page 10
```

**Comment by godmar** [comment]
No, that's not what I mean. I meant that a function 'all_projects' should list all projects (from page 1 to page n).  Right now, the only way I've found to list all projects is:

    for page in count(1):
        projects = gl.all_projects(page=page)
        if len(projects) == 0:
            break
        <process page here>

Is this the only way?

**Comment by gpocentek** [comment]
Sorry, I misunderstood your question.

AFAIK the gitlab API doesn't provide a method to list all the projects without pagination, so a loop is probably the only way to get what you want.
