### ISSUE TITLE
This warning will only appear once by default. InsecureRequestWarning

### ISSUE THREAD

**Issue by xied75** [gpocentek/python-gitlab#57]
Dear all,

```
dong@dong-Ubuntu:~$ gitlab project list
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py:730: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html (This warning will only appear once by default.)
  InsecureRequestWarning)
```
It's showing every time. Anything I can do to turn it off?

Best,

Dong

**Comment by gpocentek** [comment]
This warning is raised by urllib3 through the requests package. The requests dev team doesn't want to remove the warning, and I tend to agree with them (see https://github.com/kennethreitz/requests/issues/2214).

If you really don't want to see the warning, you can add a call to `requests.packages.urllib3.disable_warnings()` in the `gitlab` script. Or use a shell redirection (`2>/dev/null`).
