### ISSUE TITLE
cli error references unknown config entry

### ISSUE THREAD

**Issue by TobyHFerguson** [gpocentek/python-gitlab#61]
I have a config file:
```
cat ~/.python-gitlab.cfg
[global]
url=http://ca-ovsx32:8888
private_token=hmy-BNCwmRChRveoUsds
```

I tried listing the users:

```
[toby.ferguson@ca-ovsx32 ~]$ gitlab -v user list
Impossible to get the gitlab id (not specified in config file)
```
but what is the gitlab id? There's no mention of this keyword for the config file? I tried `id`, `username` & `user_name`Indeed, there's no complete list of keywords :-(

**Comment by TobyHFerguson** [comment]
I realized that the config file HAD to have general syntax

```
 [global] 
default = [XXXX]   


[XXX]
```
to work - this could be documented more clearly.

**Comment by t2ac32** [comment]
@TobyHFerguson  could you elaborate a bit more I have  the same problem.
