### ISSUE TITLE
Can't update project via cli

### ISSUE THREAD

**Issue by iakovgan** [gpocentek/python-gitlab#62]
running: 

```
gitlab project update --id=ID --default-branch=master
```
returns error ~ `function do_get accepts 4 arguments, 2 given`. 
 

Please check this line:
https://github.com/gpocentek/python-gitlab/blob/master/gitlab/cli.py#L185

Function actually accepts 4 arguments. Looks like copypaste issue. 
https://github.com/gpocentek/python-gitlab/blob/master/gitlab/cli.py#L165

ps 
And thank you for a nice tool! It is most helpfull.

**Comment by iakovgan** [comment]
Awsome! Thank. 


I just have a doubt about `project update`. i gues it should require `namespace` or `namespace-id` since one project can be found in different spaces as well as in a personal namespace. 

Also what is the behavior when we find multiple objects?

**Comment by gpocentek** [comment]
namespace should stay optional, because you don't *have* to use it. TBH I'm not sure what the behavior would be if multiple objects exist.
