### ISSUE TITLE
Iteration of results

### ISSUE THREAD

**Issue by jantman** [gpocentek/python-gitlab#63]
I'm using GitLab CE 7.12.2, and trying to list users via the API. I have 162 users. After connecting to GitLab using python-gitlab 0.9.2 from PyPi (my connection is ``self.conn``), ``self.conn.User()`` returns a list with 20 items, a fraction of my users.

The [GitLab API documentation](https://github.com/gitlabhq/gitlabhq/tree/master/doc/api#pagination) says that it paginates responses with a default of 20 results per response.

It appears that python-gitlab is ignoring the pagination. The only use of the "page" response attribute that I see in the source code is on [line 341](https://github.com/gpocentek/python-gitlab/blob/master/gitlab/__init__.py#L341) where it's deleted before passing to the constructor.

Could you please either implement pagination of responses so python-gitlab doesn't silently ignore results, or at least mention in the docs that this is happening?

Thanks.

**Comment by gpocentek** [comment]
You can use the ``page`` and ``per_page`` arguments.

From the README:

`````python
for g in gl.Group(page=1, per_page=10):
    print (g)
`````

**Comment by jantman** [comment]
@gpocentek Ok, I'd missed that, sorry. But doesn't that just add those as query parameters and build a URL based on them? The [API Docs for Pagination](https://github.com/gitlabhq/gitlabhq/tree/master/doc/api#pagination) specifically say,

> Link headers are send back with each response. These have rel prev/next/first/last and contain the relevant URL. Please use these instead of generating your own URLs.

**Comment by dserodio** [comment]
The "automatic" pagination proposed by @jantman would be a great addition. There's no way to find out the max number of pages for a given resource

**Comment by gpocentek** [comment]
Closing as this as been implemented in #64 . Thanks.
