### ISSUE TITLE
can't delete repo via gitlab command line

### ISSUE THREAD

**Issue by zesty** [gpocentek/python-gitlab#65]
$ gitlab project list
id: 6
path: UBER

$ gitlab project delete --id 6
Traceback (most recent call last):
  File "/usr/bin/gitlab", line 9, in <module>
    load_entry_point('python-gitlab==0.9', 'console_scripts', 'gitlab')()
  File "/usr/lib/python2.7/dist-packages/gitlab/cli.py", line 340, in main
    o = globals()['do_%s' % action.lower()](cls, gl, what, args)
  File "/usr/lib/python2.7/dist-packages/gitlab/cli.py", line 185, in do_delete
    o = do_get(cls, args)
TypeError: do_get() takes exactly 4 arguments (2 given)

can create:
$ gitlab project create --name FISH
id: 7
path: fish

**Comment by gpocentek** [comment]
Which version of python-gitlab are you using?

**Comment by zesty** [comment]
0.9-1

**Comment by gpocentek** [comment]
An upgrade to 0.9.2 should fix it. Please reopen if the problem still exists.
