### ISSUE TITLE
Python GitLab - update 'Linked LDAP groups'

### ISSUE THREAD

**Issue by zipi123** [gpocentek/python-gitlab#67]
Hi :),

in Python GitLab, how can i update 'Linked LDAP groups' : LDAP Group cn, LDAP Access...

git = gitlab.Gitlab('http://gitlab..., email='..', password='.....')
git.auth()
	dict = {
			'name': 'TestGroup4',
			'path': 'TestGroup4',
			'ldap_group_links':[{'cn':'Cloud Management Tools','group_access':50,  
                        'provider':'ldapmain'}]
			
			}
g = git.Group(dict)
g.save()

**Comment by gpocentek** [comment]
This is not yet supported in python-gitlab.

**Comment by gpocentek** [comment]
Linked LDAP groups is an Enterprise edition feature. I don't have access to this edition so it'll be complicated to write the code to support this. Patches are welcome.
