### ISSUE TITLE
How to create Issues via python-gitlab?

### ISSUE THREAD

**Issue by waldemar21** [gpocentek/python-gitlab#71]
Hello,

i want to use python-gitlab to create issues, but could not figure how it works? 

Two questions:
* 1) Can this script create Issues?
* 2) If yes, how can i create new Issues ? :)

Hope someone can help me out.

**Comment by gpocentek** [comment]
Creating/Editing issues is not possible at the moment, but shouldn't be too difficult to implement.

**Comment by waldemar21** [comment]
Okay, thanks for the info :)

**Comment by gpocentek** [comment]
This is actually already available :

`````
gitlab project-issue create --project-id 3 --title 'issue1' --description "This is a comment" --labels foo,bar
`````
