### ISSUE TITLE
Modify a group member

### ISSUE THREAD

**Issue by Asher256** [gpocentek/python-gitlab#73]
Hi Gauvain,

Thank you for this great module. I like it because it follows the philosophy / coding style of Python (compared to pyapi-python) .

I have a little quesiton:

I tried to modify a group member:
```
for member in group.Member(all=True):
    if member.id == 12:
        member.access_level = 50
        member.save()
```

But it raised an exception that says "the function is not implemented".

Is there a way to modify a group member with the current version of python-gitlab?

Cheers,
Asher

PS: I remember you. You contributed few years ago with a Debian package for one of my free softwares 'Jargon Informatique' ;-) . Le monde est petit !

**Comment by gpocentek** [comment]
It should work now, let me know if this is still a problem.
