### ISSUE TITLE
'Gitlab' object has no attribute 'projects'

### ISSUE THREAD

**Issue by sbanerjee23** [gpocentek/python-gitlab#81]
I installed python-gitlab with `pip` and was able to connect to with my private token and print my user information successfully, but when I try and generate a list of projects from `gl.projects.list()` I get an `AttributeError: 'Gitlab' object has no attribute 'projects'`. 

`gl` still seems to have `Group, Hook, Issue, Project, Team` etc. 

I tried for both root and non-root users. Thanks for the help.

**Comment by gpocentek** [comment]
The README on github is not in sync with the release. Please use https://github.com/gpocentek/python-gitlab/tree/0.10

**Comment by gpocentek** [comment]
Version 0.11 has been published, and the doc is now on readthedocs.
