### ISSUE TITLE
Improve documentation for 0.11

### ISSUE THREAD

**Issue by sashkab** [gpocentek/python-gitlab#83]
Unable to replace File -> files:

I've got this code, which works:

```python
        p = self.projects.get(id=project_id)
        f = p.File(file_path=file_path, ref=ref)
```

After upgrade to 0.11 getting DepricationWarnings, so replacing it with... 

```
(Pdb++) p.files.get()
*** TypeError: get() takes exactly 2 arguments (1 given)

(Pdb++) p.files.get(project_id=project_id, file_path=file_path, ref=ref)
*** TypeError: get() takes exactly 2 arguments (1 given)

(Pdb++) p.files.get({'project_id':project_id, 'file_path':file_path, 'ref': ref})
<gitlab.objects.ProjectFile object at 0x919b2b0>

(Pdb++) p.files.get({'project_id': 1, 'ref': 'master', 'file_path': 'requirements.txt'}).get()
*** TypeError: get() takes exactly 3 arguments (1 given)
```

And I'm stuck. Same thing with creating new issue comments. 

Could you please add more documentation on how to properly move, since it seems syntax changes more dramatically than with Project -> projects, Issue -> issues.

**Comment by gpocentek** [comment]
http://python-gitlab.readthedocs.org/en/latest/upgrade-from-0.10.html should help. Let me know if you need more information.

**Comment by sashkab** [comment]
I looked there, I looked into the code and it didn't help me.  

Logic says that I need to pass to `p.files.get(file_path, ref)`, but it doesn't work. What am I missing? Do I need to get branch first and then get files from the branch?

ie:

```
p  = self.projects.get(id=project_id)
b = p.branch.get(ref=ref)
f = b.files.get(file_path).content
```

**Comment by gpocentek** [comment]
You actually had the correct syntax but there's in bug in the BaseManager class that made your code fail. I pushed commit 0e0c81d2 which should fix it.

The syntax is:
`````
p = gl.projects.get(some_project_id)
f = p.files.get(file_path=file_path, ref=ref)
content = base64.b64decode(f.content)
`````

Could you confirm that the patch works for you? If it's OK I'll push a new release. Thank you.

**Comment by sashkab** [comment]
Yes, this changes solved the problem with the downloading of the file, but introduces a debug output from somewhere... 

The only remaining case I have now is creating a note for the project. 

Old code was:

```python
        p = self.projects.get(id=project_id).
        i = p.issues.get(project_id=project_id, id=issue_id)
        if i.canUpdate:
            n = i.Note({
                'project_id': project_id,
                'issue_id': issue_id,
                'body': body,
            })
            n.save()
```

Now replacing `Note` into `notes.create`:

```python
>>> n = i.notes.create({'project_id': project_id, 'issue_id': issue_id, 'body': 'test'})
>>> n.save()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/b/.virtualenvs/bootstrap/lib/python2.7/site-packages/gitlab/objects.py", line 321, in save
    self._update(**kwargs)
  File "/home/b/.virtualenvs/bootstrap/lib/python2.7/site-packages/gitlab/objects.py", line 314, in _update
    raise NotImplementedError
NotImplementedError
```

**Comment by sashkab** [comment]
Do I understand correctly, that `n.save()` no longer required?

**Comment by gpocentek** [comment]
n.save() is no longer needed. I'll check what's happening with the note creation.

**Comment by sashkab** [comment]
Then there is no issues with note creation. 

Thank you.

**Comment by gpocentek** [comment]
OK. Thank you for you report and tests!

**Comment by sashkab** [comment]
Please make sure to disable debug output you added recently :)

**Comment by gpocentek** [comment]
It's done already :)

I'll push a new release after adding some unit and functional tests.
