### ISSUE TITLE
Gitlab.from_config not present 

### ISSUE THREAD

**Issue by mbortola** [gpocentek/python-gitlab#86]
Hi
the following statement 

> gl = gitlab.Gitlab.from_config('somewhere', ['xxxxx'])

refers to a method not present in python-gitlab 0.9.2, that is the version that my pip download (i am using python 2.7)

Is it correct? shoud i usa some different method or other?

Thanks

**Comment by gpocentek** [comment]
Hello,

I recommend to upgrade to a more recent version (`pip install --upgrade python-gitlab`). If this is not possible, you won't be able to use the `from_config` method. You can use the REAME file for the 0.9.2 version in this case: https://github.com/gpocentek/python-gitlab/tree/0.9.2
