### ISSUE TITLE
project-member create failing with 404: #<ActiveModel::Errors:0x000000078945c0> Not Found error

### ISSUE THREAD

**Issue by PHinker** [gpocentek/python-gitlab#87]
![bugreport](https://cloud.githubusercontent.com/assets/14066018/12634074/bc5e9718-c533-11e5-9aab-5a09f1cb983f.png)

Running python 2.7.10 on Fedora 22
GitLab Community Edition 8.4.0
The user id [7203293] does exist and I am admin on the site so I have permissions (I can perform the member create through the website interface).  I have verified that the API token I'm using is correct. I have upgraded to the latest python-gitlab release.

**Comment by gpocentek** [comment]
I'm not able to reproduce the problem here. The returned error looks like an internal gitlab error, and not a python backtrace. Could you try to run the request using curl, with something like this:

`````
curl -H "PRIVATE-TOKEN: you_token_here" \
  -X POST "http://gitlab_server/api/v3/projects/344/members" \
  --data '{"user_id": 7203293, "access_level": 40}'
`````

**Comment by PHinker** [comment]
Thanks for the quick response.  The curl command returned the following:

<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor=”white”>
<center><h1>301 Moved permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>

**Comment by gpocentek** [comment]
Looks like you have an http(s) redirection. Add the `-L` option to the curl command.

**Comment by gpocentek** [comment]
@PHinker: Any news?

**Comment by PHinker** [comment]
This appears to have been a misconfiguration in the gitlab server.  After a recent server upgrade, this problem has gone away
