### ISSUE TITLE
Why not use an option parser?

### ISSUE THREAD

**Issue by samrocketman** [gpocentek/python-gitlab#9]
Is there a reason you're rolling your own option parsing rather than using the well tested optparse or argparse?  This regards the [`gitlab`](https://github.com/gpocentek/python-gitlab/blob/master/gitlab) CLI utility.

**Comment by gpocentek** [comment]
python-gitlab now uses argparse.

**Comment by samrocketman** [comment]
everything is awesome :dancers:
