### ISSUE TITLE
Don't enable DeprecationWarning

### ISSUE THREAD

**Issue by sashkab** [gpocentek/python-gitlab#96]
DeprecationWarning is [ignored by default](https://docs.python.org/2/library/warnings.html#warning-categories) in Python. 

Why did you [enable it globally](https://github.com/gpocentek/python-gitlab/blob/0.12.1/gitlab/__init__.py#L41)? If you want to warn users on deprecations, you can enable them for your module only.

**Comment by theherk** [comment]
This is a bit of information overload. Leaving the default behavior here would be great.
